CREATE TABLE IF NOT EXISTS provider_collection (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ticket_id INT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    currency VARCHAR(10) NOT NULL,
    collection_date DATE NOT NULL,
    provider_name VARCHAR(255) NOT NULL,
    provider_ref VARCHAR(255),
    tour_name VARCHAR(255) NOT NULL,
    tour_group_name VARCHAR(255) NOT NULL,
    customer_name VARCHAR(255) NOT NULL,
    hotel_name VARCHAR(255),
    room_number VARCHAR(50),
    guide_name VARCHAR(255),
    adult_count INT NOT NULL DEFAULT 0,
    child_count INT NOT NULL DEFAULT 0,
    free_count INT NOT NULL DEFAULT 0,
    adult_price DECIMAL(10,2) NOT NULL,
    half_price DECIMAL(10,2) NOT NULL,
    total_amount DECIMAL(10,2) NOT NULL,
    comment TEXT,
    transaction_code VARCHAR(6) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ticket_id) REFERENCES reservation_tickets(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 